language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '12'
  - '13'
script:
  - npm run build && npm link
  - cd $TRAVIS_BUILD_DIR/examples/scaffold && klap build
  - cd $TRAVIS_BUILD_DIR/examples/scaffold-typescript && klap build
  - cd $TRAVIS_BUILD_DIR/examples/react-component && klap build
